homepage:
    pattern:  /
    defaults: { _controller: FrameworkBundle:Default:index }

hello:
    resource: "@HelloBundle/Resources/config/routing.yml"
    
ola:
    resource: "@OlaBundle/Resources/config/routing.yml"

direct:
    resource: "@DirectBundle/Resources/config/routing.yml"
